use employetracker;
desc deparment;
insert into deparment(deparmentname) values("IT");
insert into deparment(deparmentname) values("HR");
insert into deparment(deparmentname) values("Marketing");
insert into deparment(deparmentname) values("Sales");
insert into deparment(deparmentname) values("PR");
select * from deparment;
desc positions;
insert into positions(title, salary, deparment_id)values("Manager", 20, 1);
insert into positions(title, salary, deparment_id)values("Manager", 20, 2);
insert into positions(title, salary, deparment_id)values("Manager", 20, 3);
insert into positions(title, salary, deparment_id)values("Manager", 20, 4);
insert into positions(title, salary, deparment_id)values("Manager", 20, 5);
insert into positions(title, salary, deparment_id)values("Intern", 12, 1);
insert into positions(title, salary, deparment_id)values("Intern", 12, 2);
insert into positions(title, salary, deparment_id)values("Intern", 12, 3);
insert into positions(title, salary, deparment_id)values("Intern", 12, 4);
insert into positions(title, salary, deparment_id)values("Intern", 12, 5);
insert into positions(title, salary, deparment_id)values("Team Leader", 17, 1);
insert into positions(title, salary, deparment_id)values("Team Leader", 17, 2);
insert into positions(title, salary, deparment_id)values("Team Leader", 17, 3);
insert into positions(title, salary, deparment_id)values("Team Leader", 17, 4);
insert into positions(title, salary, deparment_id)values("Team Leader", 17, 5);
select * from positions;
desc employe;
insert into employe(first_name, last_name, positions_id, manager_id)values("John","Doe", 1, null);
insert into employe(first_name, last_name, positions_id, manager_id)values("John","Smith", 2, null);
insert into employe(first_name, last_name, positions_id, manager_id)values("Billy","Doe", 3, null);
insert into employe(first_name, last_name, positions_id, manager_id)values("Dave","Smith", 4, null);
insert into employe(first_name, last_name, positions_id, manager_id)values("Sam","Miller", 5, null);
insert into employe(first_name, last_name, positions_id, manager_id)values("Johny","Doe", 6, 1);
insert into employe(first_name, last_name, positions_id, manager_id)values("Johny","Smith", 7, 2);
insert into employe(first_name, last_name, positions_id, manager_id)values("Bill","Doe", 8, 3);
insert into employe(first_name, last_name, positions_id, manager_id)values("Davey","Smith", 9, 4);
insert into employe(first_name, last_name, positions_id, manager_id)values("Samy","Miller", 10, 5);
insert into employe(first_name, last_name, positions_id, manager_id)values("Johny","Do", 11, 1);
insert into employe(first_name, last_name, positions_id, manager_id)values("Johny","Smi", 12, 2);
insert into employe(first_name, last_name, positions_id, manager_id)values("Bills","Doe", 13, 3);
insert into employe(first_name, last_name, positions_id, manager_id)values("Daviey","Smithy", 14, 4);
insert into employe(first_name, last_name, positions_id, manager_id)values("Samy","Millers", 15, 5);
select * from employe;


